# AUTOGENERATED! DO NOT EDIT! File to edit: 07_diffquant_utils.ipynb (unless otherwise specified).

__all__ = ['get_condpairname']

# Cell
def get_condpairname(condpair):
    return f"{condpair[0]}_VS_{condpair[1]}"