---
#this file determines the parameters used to convert long format tables as e.g. produced by Spectronaut or DIA-NN into a wide table format

maxquant_peptides:
  format: widetable
  quant_prefix: "Intensity "
  protein_cols:
   - Leading razor protein
  ion_cols:
   - Sequence
  filters:
    reverse:
      param: Reverse
      comparator: "!="
      value: "+"
    contaminant:
      param: Potential contaminant
      comparator: "!="
      value: "+"

diann_precursor:
  format: longtable
  sample_ID: Run
  quant_ID: Precursor.Quantity
  protein_cols:
   - Protein.Group
  ion_cols:
   - Precursor.Id
  filters:
    shape_quality:
      param: Quantity.Quality
      comparator: ">"
      value: 0.3


spectronaut_fragion_isotopes:
  format: longtable
  sample_ID: R.Label
  quant_ID:
    fragion: F.PeakArea
    ms1iso: FG.MS1IsotopeIntensities (Measured)
  protein_cols:
   - PG.ProteinGroups
  ion_cols:
   - FG.Id
   - F.FrgIon
   - F.FrgLossType
   - F.Charge
  split_cols:
    FG.MS1IsotopeIntensities (Measured): ";"
  ion_hierarchy:
    SEQ: 
     - PEP.StrippedSequence
    MOD: 
     - EG.ModifiedSequence
    CHARGE: 
     - FG.Charge
    FRGION: 
     - F.FrgIon
     - F.FrgLossType
     - F.Charge
    MS1ISOTOPES:
     - FG.MS1IsotopeIntensities (Measured)
  filters:
    fragion_intensity:
      param: F.PeakArea
      comparator: ">"
      value: 5.0
  # filters:
  #   decoy_filt:
  #     param: EG.IsDecoy
  #     comparator: "=="
  #     value: False
  #   shape_quality: 
  #     param: FG.ShapeQualityScore (MS2)
  #     comparator: ">"
  #     value: 0.4
  #   fragion_interference:
  #     param: F.PossibleInterference
  #     comparator: "=="
  #     value: False


spectronaut_precursor_ptm_annotated:
  format: longtable
  sample_ID: R.Label
  quant_ID: FG.Quantity
  protein_cols:
    - site_id
  ion_cols:
    - ion


spectronaut_precursor_new:
  format: longtable
  sample_ID: R.Label
  quant_ID: FG.MS2RawQuantity
  protein_cols:
   - PG.ProteinGroups
  ion_cols:
   - FG.Id
  filters:
    decoy_filt:
      param: EG.IsDecoy
      comparator: "=="
      value: False
    shape_quality: 
      param: FG.ShapeQualityScore (MS2)
      comparator: ">"
      value: 0.4

  
spectronaut_precursor:
  format: longtable
  sample_ID: R.Label
  quant_ID: FG.Quantity
  protein_cols:
   - PG.ProteinGroups
  ion_cols:
   - FG.Id

spectronaut_precursor_v2:
  format: longtable
  sample_ID: R.Label
  quant_ID: FG.Quantity
  protein_cols:
   - PG.ProteinGroups
  ion_cols:
   - EG.ModifiedPeptide
   - FG.Charge



openswath_precursor_aligned:
  format: longtable
  sample_ID: run_id
  quant_ID: Intensity
  protein_cols:
   - ProteinName
  ion_cols:
   - peptide_group_label
  filters:
    decoy:
      param: decoy
      comparator: "=="
      value: 0

openswath_pyprophet:
  format: longtable
  sample_ID: filename
  quant_ID: Intensity
  protein_cols:
   - ProteinName
  ion_cols:
   - FullPeptideName
   - Charge
  filters:
    decoy:
      param: decoy
      comparator: "=="
      value: 0

skyline_precursor:
  format: longtable
  sample_ID: ReplicateName
  quant_ID: TotalAreaFragment
  protein_cols:
   - ProteinName
  ion_cols:
   - PeptideModifiedSequence
   - PrecursorCharge

diaumpire_precursor_ms1:
  format: widetable
  protein_cols:
   - Proteins
  ion_cols:
   - Peptide Key






