---
#this file determines the parameters used to convert long format tables as e.g. produced by Spectronaut or DIA-NN into a wide table format

diann_precursor:
  sample_ID: Run
  quant_ID: Precursor.Quantity
  grouping_cols:
    protein_cols:
     - Protein.Group
    ion_cols:
     - Precursor.Id
  filters:
    shape_quality:
      param: Quantity.Quality
      comparator: ">"
      value: 0.3
  ptmsite_ids: None

