default:
  exclude_if_elements_in_mainclust_less_than:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  exclude_if_elements_in_mostcommonclust_less_than:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  exclude_if_frac_mostcommonclust_less_than:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  exclude_if_fraction_of_mainclust_smaller_than:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  exclude_if_more_clusters_than:
  - .inf
  - .inf
  - .inf
  - .inf
  - .inf
  - .inf
  exclude_if_num_mainclusts_less_than:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  exclude_if_num_mostcommonclusts_less_than:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  select_cluster:
  - -1
  - -1
  - -1
  - -1
  - -1
  - -1
  type:
  - frgion
  - ms1_isotopes
  - mod_seq_charge
  - mod_seq
  - seq
  - gene
