# AUTOGENERATED! DO NOT EDIT! File to edit: 11_multi_condition_analysis.ipynb (unless otherwise specified).

__all__ = ['StepWiseRegulationOverview']

# Cell

class StepWiseRegulationOverview():
    def __init__(self, results_dir, sorted_list_of_conditions):
        #spongebob self._multicond_data = 

