on:
  pull_request:
  workflow_dispatch:

name: Different pip installations with quick tests

jobs:
  stable_installation:
    name: Test stable pip installation on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Test pip installation with all stable dependencies
        shell: bash -l {0}
        run: |
          cd misc
          . ./stable_pip_install.sh
      - name: Unittests
        shell: bash -l {0}
        run: |
          cd tests
          . ./run_e2e_tests_quick.sh
  loose_installation:
    name: Test loose pip installation on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Test pip installation with all loose dependencies
        shell: bash -l {0}
        run: |
          cd misc
          . ./loose_pip_install.sh
      - name: Unittests
        shell: bash -l {0}
        run: |
          cd tests
          . ./run_e2e_tests_quick.sh
